package pashkov.entity;

public enum TeachingSubject {
    UKRAINIAN_LANGUAGE,LITERARY_READING,ENGLISH,I_AM_IN_THE_WORLD,MUSICAL_ART,FINE_ARTS,
    MATHEMATICS,NATURAL_SCIENCE,LABOR_TRAINING,INFORMATICS,BASICS_OF_HEALTH,PHYSICAL_CULTURE,
    FOREIGN_LITERATURE,HISTORY,THE_WORLD_HISTORY,BIOLOGY,GEOGRAPHY,PHYSICS,CHEMISTRY
}
